### ISSUE TITLE
AuthApiError: Error invoking access token hook.

### ISSUE THREAD

**Issue by Shlok-Zanwar** [supabase/auth#1523]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am trying to use Auth Hooks with a project, The project structure is very simple.
Just the authentication table and another table `pft` with `id, user_id and is_admin`

I have a postgres function for the hook which looks like this
![image](https://github.com/supabase/auth/assets/63449205/ffd8fa19-4c5d-4757-996f-bad8065e5822)
```
declare
    claims jsonb;
    is_a boolean;
  begin
    -- Check if the user is marked as admin in the profiles table
    select is_admin into is_a from pft where user_id = (event->>'user_id')::uuid;

    -- Proceed only if the user is an admin
    if is_a then
      claims := event->'claims';

      -- Check if 'app_metadata' exists in claims
      if jsonb_typeof(claims->'app_metadata') is null then
        -- If 'app_metadata' does not exist, create an empty object
        claims := jsonb_set(claims, '{app_metadata}', '{}');
      end if;

      -- Set a claim of 'admin'
      claims := jsonb_set(claims, '{app_metadata, admin}', 'true');

      -- Update the 'claims' object in the original event
      event := jsonb_set(event, '{claims}', claims);
    end if;

    -- Return the modified or original event
    return event;
  end;
```

I have enabled it in the Auth hooks page.
But when logging in I am getting these errors on the console

```
{ user: null, session: null } AuthApiError: Error invoking access token hook.
    at handleError (webpack-internal:///(action-browser)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:74:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (webpack-internal:///(action-browser)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:120:9)
    at async _request (webpack-internal:///(action-browser)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:99:18)
    at async SupabaseAuthClient.signInWithPassword (webpack-internal:///(action-browser)/./node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:343:23)
    at async loginWithEmailServer (webpack-internal:///(action-browser)/./app/server-utils/supabase-auth-actions.ts:52:29)
    at async C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:406
    at async t2 (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:6412)
    at async rS (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1369)
    at async doRender (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:1378:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:1539:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:1447:28)
    at async DevServer.renderPageComponent (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:1844:24)
    at async DevServer.renderToResponseImpl (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:1882:32)
    at async DevServer.pipeImpl (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\next-server.js:269:17)
    at async DevServer.handleRequestImpl (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\base-server.js:791:17)
    at async C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\dev\next-dev-server.js:331:20
    at async Span.traceAsyncFn (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
    at async invokeRender (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\Shlok\Documents\Projects\experiment\my-next-todo-app\node_modules\next\dist\server\lib\start-server.js:140:13) {
  __isAuthError: true,
  status: 500,
  code: 'unexpected_failure'
}
```
The reason doesn't seem to be clear.
I have spent a lot of time debugging this. 
Checking the logs I found some things

![image](https://github.com/supabase/auth/assets/63449205/109db4ad-360f-4191-986c-1f9c4f17f387)
Pasting the complete metadata :
```
[
  {
    "message": null,
    "timestamp": "2024-04-09T19:07:33Z",
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": "POST",
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "error",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "500: Error invoking access token hook.",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-yxkkzgeybuvdunvzsmfk",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": null,
    "CODE_LINE": null,
    "path": "/token",
    "component": "api",
    "project": null,
    "user_id": null,
    "auth_event": [
      {
        "action": "login",
        "actor_id": "39cd19d5-5acd-4f8c-a83a-db61fd4a5212",
        "actor_name": null,
        "actor_username": "princeshlok123@gmail.com",
        "actor_via_sso": false,
        "log_type": "account",
        "traits": [
          {
            "channel": null,
            "identity_id": null,
            "provider": "email",
            "provider_id": null,
            "provider_type": null,
            "user_email": null,
            "user_id": null,
            "user_phone": null
          }
        ]
      }
    ],
    "args": [],
    "referer": "http://localhost:3000",
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "remote_addr": "223.233.86.44",
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": "ERROR: relation \"pft\" does not exist (SQLSTATE 42P01)"
  }
]
```

Also i can see a lot of `403: invalid claim: missing sub claim`. What do they mean, Do they have anything to do with this ?

## Expected behavior
To be able to have custom RBAC in the auth token.

## System information

- OS: windows
- Browser (if applies) chrome
- Version of supabase-js: 
  ```
    "@supabase/ssr": "^0.1.0",
    "@supabase/supabase-js": "^2.42.0",
  ```
- Version of Node.js: v21.7.1

## Additional context

Please help, I have spent a lot of time debugging.,. There is no docs on this, and also the error message doesnt give any clue about whats wrong
Thanks in advance

**Comment by vasko77** [comment]
Same issue with me. Try removing the select statement 
 --select is_admin into is_a from pft where user_id = (event->>'user_id')::uuid;
and it will work.
Not sure why....

**Comment by ItaiAxelrad** [comment]
I am also seeing a `403: invalid claim: missing sub claim`. Would love to know how to troubleshoot

**Comment by J0** [comment]
Hey @vasko77 

Thanks for flagging the issue. I'll look into this

@ItaiAxelrad can I check if the missing claim issue still persists for you?

**Comment by ItaiAxelrad** [comment]
@J0 It seems to be working today, thanks!

**Comment by vasko77** [comment]
This is what fixed the issue for me. It was a security issue.
grant all
  on table public.user_roles
  to supabase_auth_admin;

**Comment by odinberre** [comment]
Currently experimenting with Auth Hooks, and have encountered this issue where I consistently receive a `403: invalid claim: missing sub claim` error. Any idea of what might be causing this?

**Comment by Ted2xmen** [comment]
Check if there is a trigger on the auth table, try disabling it. It worked for me
