### ISSUE TITLE
"Invalid Login Credientals" AuthApiError should have an error code

### ISSUE THREAD

**Issue by JeongJuhyeon** [supabase/auth#1631]
# Bug report

- [O] I confirm this is a bug with Supabase, not with my own application. 
- [O] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Docs explicitly state:

> Errors originating from the server API classed as AuthApiError **always have a code property that can be used to identify the error returned by the server**. The status property is also present, encoding the HTTP status code received in the response.

Docs also suggest:

> Do not use string matching on error messages! Always use the name and code properties of error objects to identify the situation.

## To Reproduce

Hit `auth/v1/token?grant_type=password` with an incorrect email/password combination and `-H 'x-supabase-api-version: 2024-01-01'`, the result is

`{"error":"invalid_grant","error_description":"Invalid login credentials"}`

And in supabase-js the resulting AuthApiError object is

`{"__isAuthError":true,"name":"AuthApiError","status":400,"code":undefined}`

## Expected behavior

As the docs suggest, the code should be defined.

**Comment by alex-guoba** [comment]
There exist two types of error response format in supabase/auth.

```
// OAuthError is the JSON handler for OAuth2 error responses
type OAuthError struct {
	Err             string `json:"error"`
	Description     string `json:"error_description,omitempty"`
	InternalError   error  `json:"-"`
	InternalMessage string `json:"-"`
}

// HTTPError is an error with a message and an HTTP status code.
type HTTPError struct {
	HTTPStatus      int    `json:"code"`                 // do not rename the JSON tags!
	ErrorCode       string `json:"error_code,omitempty"` // do not rename the JSON tags!
	Message         string `json:"msg"`                  // do not rename the JSON tags!
	InternalError   error  `json:"-"`
	InternalMessage string `json:"-"`
	ErrorID         string `json:"error_id,omitempty"`
}
```

I think field in OAuthError was designed to accordance with rfc 6749.
https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

**Comment by kangmingtay** [comment]
@JeongJuhyeon thanks for raising this - this is a good point though, i agree that we shouldn't be returning the oauth error struct for sign-in with password errors

@alex-guoba yup that's right, the oauth error conforms to the error response specified in the RFC

I'll discuss with the team on updating the sign-in with password errors to return a http error instead, with a proper error code, while maintaining the 400 status code returned.

**Comment by ksharinarayanan** [comment]
Hey @kangmingtay is this something that will be considered for external contributions? If yes, I can pick it up.

**Comment by jeffbmartinez** [comment]
I had the same confusion. I'm new to supabase and spent some time trying to figure out why I wasn't getting the `.code` as specified in the docs.

It looks like the `.code` is getting lost when the `httpError` function wraps the code and fmtString in a `HTTPError` type:

```
// https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/signup.go#L109
func (a *API) Signup(w http.ResponseWriter, r *http.Request) error {
	// ... nested logic ...
	// ...
	// https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/signup.go#L304C5-L304C91
	return unprocessableEntityError(ErrorCodeUserAlreadyExists, "User already registered")


// https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/errors.go#L88
func unprocessableEntityError(errorCode ErrorCode, fmtString string, args ...interface{}) *HTTPError {
	return httpError(http.StatusUnprocessableEntity, errorCode, fmtString, args...)
}


// Seems to be getting lost here, when errorCode is now called ErrorCode, without json serialization to 'code'
// This is about as far as I followed the code's flow

// https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/errors.go#L141
func httpError(httpStatus int, errorCode ErrorCode, fmtString string, args ...interface{}) *HTTPError {
	return &HTTPError{
		HTTPStatus: httpStatus,
		ErrorCode:  errorCode,
		Message:    fmt.Sprintf(fmtString, args...),
	}
}
```

For easy reference:
```
// https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/errorcodes.go#L55
const ErrorCodeUserAlreadyExists                 ErrorCode = "user_already_exists"

// https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/errorcodes.go#L3C1-L3C24
type ErrorCode = string
```

FWIW I also stumbled upon this type called `HTTPErrorResponse20240101` (https://github.com/supabase/auth/blob/9ac3cffb9dd36958fd6f221765dcebcebf1a30d4/internal/api/errors.go#L181) which seems like it was supposed to be the thing described in the current documentation as well.

Like I said, I'm new to supabase, but perhaps this helps figure out where to fix.

Or, at a minimum, it would be great to see the [documentation on expected errors](https://supabase.com/docs/reference/javascript/auth-error-codes) updated since it's currently inaccurate.

I'm happy to pitch in once a decision is made on a potential fix.

**Comment by kangmingtay** [comment]
@IPJT supabase/ssr uses the version of supabase-js installed under the hood, so you should be able to see it if you bump your supabase-js version

**Comment by lawinski** [comment]
@kangmingtay Have you discussed other OAuth errors? Currently, the `/token` endpoint can return a mix of `OAuthError` and `HTTPError` with different structures. From what I can see, it currently looks like this:

`password` → throws `HTTPError` errors
`refresh_token` → throws both `OAuthError` and `HTTPError` errors
`id_token` → throws both `OAuthError` and `HTTPError` errors
`pkce` → throws `HTTPError` errors

I understand that the `OAuthError` structure follows the RFC specification, but shouldn't it be unified? This question came up when I implemented account linking via id_token and noticed that the errors resulting from linking and id_token implementations will have different error structures.

So, should the id_token and refresh_token follow the Supabase `HTTPError` structure, or should we unify all grant types to return `OAuthError`?

**Comment by nickgieschen** [comment]
I'm getting a significant mismatch in these responses when pointing to my local supabase instance when developing locally and when pointing on the hosted version. There is also a mismatch when using the ssr client vs the browser client. 

I just brew updated, so I assume I'm using the latest cli.

This obviously and unfortunately makes developing locally impossible.

Here are the four different responses for an incorrect password:

local supabase, brower client `{"error":"invalid_grant","error_description":"Invalid login credentials"}` (This doesn't come through in the error struct via the client. Rather { error } is undefined)
local supabase, ssr client
```
{
  data: { user: null, session: null },
  error: AuthApiError: Invalid login credentials
      at handleError (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/lib/fetch.js:80:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _handleRequest (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/lib/fetch.js:123:9)
      at async _request (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/lib/fetch.js:105:18)
      at async SupabaseAuthClient.signInWithPassword (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:343:23)
      at async $$ACTION_0 (webpack-internal:///(action-browser)/./src/app/(auth)/sign-in/actions.ts:17:17)
      at async /Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
      at async rS (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
      at async r2 (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
      at async doRender (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1438:30)
      at async cacheEntry.responseCache.get.routeKind (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1599:28)
      at async DevServer.renderToResponseWithComponentsImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1507:28)
      at async DevServer.renderPageComponent (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1924:24)
      at async DevServer.renderToResponseImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1962:32)
      at async DevServer.pipeImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:920:25)
      at async NextNodeServer.handleCatchallRenderRequest (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/next-server.js:272:17)
      at async DevServer.handleRequestImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:816:17)
      at async /Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/dev/next-dev-server.js:339:20
      at async Span.traceAsyncFn (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/trace/trace.js:154:20)
      at async DevServer.handleRequest (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
      at async invokeRender (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/router-server.js:174:21)
      at async handleRequest (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/router-server.js:353:24)
      at async requestHandlerImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/router-server.js:377:13)
      at async Server.requestListener (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/start-server.js:141:13) {
    __isAuthError: true,
    status: 400,
    code: undefined
  }
}
```


hosted supabase, browser client `{"code":"invalid_credentials","message":"Invalid login credentials"}`
hosted supabase, ssr client
```
{
  data: { user: null, session: null },
  error: AuthApiError: Invalid login credentials
      at handleError (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/lib/fetch.js:80:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _handleRequest (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/lib/fetch.js:123:9)
      at async _request (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/lib/fetch.js:105:18)
      at async SupabaseAuthClient.signInWithPassword (webpack-internal:///(action-browser)/../../node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:343:23)
      at async $$ACTION_0 (webpack-internal:///(action-browser)/./src/app/(auth)/sign-in/actions.ts:17:17)
      at async /Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
      at async rS (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
      at async r2 (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
      at async doRender (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1438:30)
      at async cacheEntry.responseCache.get.routeKind (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1599:28)
      at async DevServer.renderToResponseWithComponentsImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1507:28)
      at async DevServer.renderPageComponent (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1924:24)
      at async DevServer.renderToResponseImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:1962:32)
      at async DevServer.pipeImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:920:25)
      at async NextNodeServer.handleCatchallRenderRequest (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/next-server.js:272:17)
      at async DevServer.handleRequestImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/base-server.js:816:17)
      at async /Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/dev/next-dev-server.js:339:20
      at async Span.traceAsyncFn (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/trace/trace.js:154:20)
      at async DevServer.handleRequest (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
      at async invokeRender (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/router-server.js:174:21)
      at async handleRequest (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/router-server.js:353:24)
      at async requestHandlerImpl (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/router-server.js:377:13)
      at async Server.requestListener (/Users/nick/dev/my-projects/soundmarket/node_modules/next/dist/server/lib/start-server.js:141:13) {
    __isAuthError: true,
    status: 400,
    code: 'invalid_credentials'
  }
}
```

**Comment by riccardolardi** [comment]
Same behaviour as @nickgieschen, locally I don't get a error code but "undefined" instead.
