### ISSUE TITLE
Cannot Use Both Email and Phone Providers Simultaneously 

### ISSUE THREAD

**Issue by MuddasirAlgoace** [supabase/auth#1840]
I am trying to register a user using both email and phone authentication in Flutter app with Supabase, but encountering the following error:

149 - assert((email != null && phone == null) || (email == null && phone != null),
150 - 'You must provide either an email or phone number');
This error arises because Supabase currently enforces a condition where only one of either email or phone is provided for user signup. However, I want to allow both email and phone parameters to be provided simultaneously, as it would make verification easier before future authentications.

Is there a way to modify or extend the logic in Supabase to support both email and phone authentication providers during signup? and their provider must be working on login seprately.

pos: I am using twilio provider for phone

**Comment by J0** [comment]
>This error arises because Supabase currently enforces a condition where only one of either email or phone is provided for user signup. However, I want to allow both email and phone parameters to be provided simultaneously, as it would make verification easier before future authentications.

Hey!

Thanks for the query, unfortunately this is right - we only allow signup with one method at a time (e.g. `signUp({phone, password})` or `signUp({email,password})` You can create an account with email and add a phone number via `updateUser` though or vice versa.

>and their provider must be working on login seprately.

To clarify, is the team hoping to have two separate accounts? (e.g. email would be one account, and phone on another). For that scenario it's possible to call sign up twice (first with phone, second with email) and there should be two separate accounts.

Let us know

**Comment by MuddasirAlgoace** [comment]
@J0 Can you please share an example?

**Comment by ab-elhaddad** [comment]
Hi @muddasirAlgo, this is how I am resolving this issue in my node.js app. I hope it helps.
```javascript
const { data: { user } } = await supabase.auth.signUp({
   email: userData.email,
   password: userData.password,
 });

 await supabase.auth.admin.updateUserById(user.id, { phone: userData.phone });
```

**Comment by MehulDokania** [comment]
@J0 Say we want to signup user with email but also link their phone number to the account. For this say initially with signup user with email otp, now when trying to verify phone, a separate entry is created by supabase, so we cannot add this phone number to exisiting email entry (since we cannot create duplicate entry in a emal/phone column).

What is the solution here to have user link their verified-email and verified-phone to the same user UID. The example shared by @ab-elhaddad, has the issue that phone is not verified but updated.

Appreciate any insight!

cc: @cstockton  @hf

**Comment by cstockton** [comment]
@MehulDokania When you update the user with a new phone number it should send an SMS confirmation unless you have "SMS Auto-confirm" enabled in your phone provider setting:
https://github.com/supabase/auth/blob/master/internal/api/user.go#L250

You will then need to call the [verify endpoint](https://supabase.com/docs/reference/javascript/auth-verifyotp).
```ts
const { data, error } = await supabase.auth.verifyOtp({ phone, token, type: 'phone_change'})
```

The token should be provided by the user from the phone confirmation sms we sent. Once verified the user should be able to signin with either phone or email.

**Comment by luckyxhu** [comment]
After link user phone and login with phone OTP will throw error (but phone + password login is ok): 

```
TypeError: Cannot create property 'user' on string '{"access_token":"...",  "token_type": "bearer", "expires_in": 3600, "expires_at": 1766606755, "refresh_token": "usmnoul4pawe", "user": { "id": "c38a94da-1fd0-4f23-ab24-964ed90e0f9b",  "aud": "authenticated", "role": "authenticated", ...}}'

at SupabaseAuthClient._recoverAndRefresh (/Users/xiaohu/bitbot/bot/app/web/node_modules/.vite/deps_ssr/chunk-UJNUG53R.js:10522:33)
at SupabaseAuthClient._initialize (/Users/xiaohu/bitbot/bot/app/web/node_modules/.vite/deps_ssr/chunk-UJNUG53R.js:9064:7)
at /Users/xiaohu/bitbot/bot/app/web/node_modules/.vite/deps_ssr/chunk-UJNUG53R.js:9015:16
```

Environment:
- react-router: "^7.11.0" (framework mode)
- @supabase/supabase-js: "^2.89.0"
- @supabase/ssr: "^0.8.0"

code
---
Both `supabase.auth.signInWithOtp()` and `supabase.auth.verifyOtp()` return success, but redirect page will throw error.

step 1:

```ts
  const { error } = await supabase.auth.signInWithOtp({
    phone: parsed.data.phone,
    options: {
      captchaToken: parsed.data.captchaToken,
      shouldCreateUser: true,
      data: {
        name: `user-${(Math.random() * 100000).toFixed(0)}`,
      },
    },
  });
```

step 2:

```ts
const { error, data } = await supabase.auth.verifyOtp({
    phone: parsed.data.phone,
    token: parsed.data.otp,
    type: "sms",
    options: {
      captchaToken: parsed.data.captchaToken,
    },
  });

return redirect('/', { headers });
```
